package colors

import "github.com/dos-2/oddshub/models"

var WorldCupTeamColorMap = map[string]models.TeamColors{
	"Argentina":              {PrimaryColor: "#75AADB", SecondaryColor: "#FFFFFF"},
	"Albania":                {PrimaryColor: "#8C1515", SecondaryColor: "#000000"},
	"Australia":              {PrimaryColor: "#1A428A", SecondaryColor: "#FFCD00"},
	"Belgium":                {PrimaryColor: "#ED2939", SecondaryColor: "#FFDF00"},
	"Bolivia":                {PrimaryColor: "#F5F5F5", SecondaryColor: "#0000FF"},
	"Brazil":                 {PrimaryColor: "#008000", SecondaryColor: "#FFD700"},
	"Colombia":               {PrimaryColor: "#FFD700", SecondaryColor: "#0033A0"},
	"Costa Rica":             {PrimaryColor: "#FFFFFF", SecondaryColor: "#0033A0"},
	"Croatia":                {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Denmark":                {PrimaryColor: "#C60C30", SecondaryColor: "#FFFFFF"},
	"Egypt":                  {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"England":                {PrimaryColor: "#FFFFFF", SecondaryColor: "#0033A0"},
	"France":                 {PrimaryColor: "#0055A4", SecondaryColor: "#FFFFFF"},
	"Germany":                {PrimaryColor: "#000000", SecondaryColor: "#FFFFFF"},
	"Iran":                   {PrimaryColor: "#FFFFFF", SecondaryColor: "#EA1E2F"},
	"Japan":                  {PrimaryColor: "#0056A0", SecondaryColor: "#FFFFFF"},
	"Mexico":                 {PrimaryColor: "#006847", SecondaryColor: "#FFFFFF"},
	"Morocco":                {PrimaryColor: "#006233", SecondaryColor: "#FFA500"},
	"Netherlands":            {PrimaryColor: "#FFA500", SecondaryColor: "#FFFFFF"},
	"Nigeria":                {PrimaryColor: "#008753", SecondaryColor: "#FFFFFF"},
	"Panama":                 {PrimaryColor: "#FFD700", SecondaryColor: "#0033A0"},
	"Peru":                   {PrimaryColor: "#DA291C", SecondaryColor: "#FFFFFF"},
	"Poland":                 {PrimaryColor: "#DC143C", SecondaryColor: "#FFFFFF"},
	"Portugal":               {PrimaryColor: "#006600", SecondaryColor: "#FF0000"},
	"Russia":                 {PrimaryColor: "#FFFFFF", SecondaryColor: "#D52B1E"},
	"Saudi Arabia":           {PrimaryColor: "#006736", SecondaryColor: "#FFFFFF"},
	"Senegal":                {PrimaryColor: "#FFD700", SecondaryColor: "#00853F"},
	"Serbia":                 {PrimaryColor: "#DC1E35", SecondaryColor: "#FFFFFF"},
	"South Korea":            {PrimaryColor: "#B31B1B", SecondaryColor: "#0033A0"},
	"Spain":                  {PrimaryColor: "#EF3340", SecondaryColor: "#FFCD00"},
	"Sweden":                 {PrimaryColor: "#006AA7", SecondaryColor: "#FFD700"},
	"Switzerland":            {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Tunisia":                {PrimaryColor: "#E52628", SecondaryColor: "#FFFFFF"},
	"Uruguay":                {PrimaryColor: "#FCD116", SecondaryColor: "#0033A0"},
	"Algeria":                {PrimaryColor: "#DA291C", SecondaryColor: "#FFFFFF"},
	"Angola":                 {PrimaryColor: "#FFD700", SecondaryColor: "#000000"},
	"Cameroon":               {PrimaryColor: "#FEDF00", SecondaryColor: "#008000"},
	"Chile":                  {PrimaryColor: "#FF0000", SecondaryColor: "#0033A0"},
	"Côte d'Ivoire":          {PrimaryColor: "#FFD700", SecondaryColor: "#0055A4"},
	"Ecuador":                {PrimaryColor: "#FFD700", SecondaryColor: "#0033A0"},
	"Ghana":                  {PrimaryColor: "#006233", SecondaryColor: "#FFA500"},
	"Honduras":               {PrimaryColor: "#006847", SecondaryColor: "#FFFFFF"},
	"Ivory Coast":            {PrimaryColor: "#FFD700", SecondaryColor: "#0055A4"},
	"Jamaica":                {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"New Zealand":            {PrimaryColor: "#FFFFFF", SecondaryColor: "#000000"},
	"Paraguay":               {PrimaryColor: "#0033A0", SecondaryColor: "#FFFFFF"},
	"South Africa":           {PrimaryColor: "#FFD700", SecondaryColor: "#006233"},
	"Trinidad and Tobago":    {PrimaryColor: "#FFFFFF", SecondaryColor: "#FFD700"},
	"USA":                    {PrimaryColor: "#B31B1B", SecondaryColor: "#FFFFFF"},
	"Zambia":                 {PrimaryColor: "#008000", SecondaryColor: "#FFFFFF"},
	"Austria":                {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Belarus":                {PrimaryColor: "#FFD700", SecondaryColor: "#D72B2B"},
	"Bosnia and Herzegovina": {PrimaryColor: "#0033A0", SecondaryColor: "#FFFFFF"},
	"Bulgaria":               {PrimaryColor: "#FFFFFF", SecondaryColor: "#008000"},
	"Czech Republic":         {PrimaryColor: "#D7141A", SecondaryColor: "#FFFFFF"},
	"Finland":                {PrimaryColor: "#FFFFFF", SecondaryColor: "#003580"},
	"Greece":                 {PrimaryColor: "#0D5EAF", SecondaryColor: "#FFFFFF"},
	"Hungary":                {PrimaryColor: "#C7242A", SecondaryColor: "#FFFFFF"},
	"Iceland":                {PrimaryColor: "#0048C9", SecondaryColor: "#FFFFFF"},
	"Italy":                  {PrimaryColor: "#FFFFFF", SecondaryColor: "#007EC5"},
	"North Macedonia":        {PrimaryColor: "#E41E20", SecondaryColor: "#FFD700"},
	"Norway":                 {PrimaryColor: "#EF2B2D", SecondaryColor: "#FFFFFF"},
	"Republic of Ireland":    {PrimaryColor: "#008C45", SecondaryColor: "#FFFFFF"},
	"Romania":                {PrimaryColor: "#FF0000", SecondaryColor: "#002B7F"},
	"Scotland":               {PrimaryColor: "#0059A6", SecondaryColor: "#FFFFFF"},
	"Slovakia":               {PrimaryColor: "#0055A4", SecondaryColor: "#D7141A"},
	"Slovenia":               {PrimaryColor: "#003399", SecondaryColor: "#FFFFFF"},
	"Turkey":                 {PrimaryColor: "#E30A17", SecondaryColor: "#FFFFFF"},
	"Ukraine":                {PrimaryColor: "#FFD700", SecondaryColor: "#0033A0"},
	"Wales":                  {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Azerbaijan":             {PrimaryColor: "#3C3B6E", SecondaryColor: "#D20012"},
	"Armenia":                {PrimaryColor: "#D10000", SecondaryColor: "#0033A0"},
	"Georgia":                {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Kazakhstan":             {PrimaryColor: "#00A2DF", SecondaryColor: "#FFFFFF"},
	"Kyrgyzstan":             {PrimaryColor: "#FFD700", SecondaryColor: "#0051A7"},
	"Moldova":                {PrimaryColor: "#FFD700", SecondaryColor: "#002B7F"},
	"Tajikistan":             {PrimaryColor: "#C60C30", SecondaryColor: "#FFFFFF"},
	"Turkmenistan":           {PrimaryColor: "#00A2DF", SecondaryColor: "#FFFFFF"},
	"Uzbekistan":             {PrimaryColor: "#00A2DF", SecondaryColor: "#FFFFFF"},
}
