package colors

import "oddshub/models"

var MLBTeamColorMap = map[string]models.TeamColors{
	"Arizona Diamondbacks":  {PrimaryColor: "#A71930", SecondaryColor: "#E3D4AD"},
	"Atlanta Braves":        {PrimaryColor: "#CE1141", SecondaryColor: "#13274F"},
	"Baltimore Orioles":     {PrimaryColor: "#DF4601", SecondaryColor: "#000000"},
	"Boston Red Sox":        {PrimaryColor: "#BD3039", SecondaryColor: "#0D2B56"},
	"Chicago White Sox":     {PrimaryColor: "#000000", SecondaryColor: "#C4CED4"},
	"Chicago Cubs":          {PrimaryColor: "#CC3433", SecondaryColor: "#0E3386"},
	"Cincinnati Reds":       {PrimaryColor: "#C6011F", SecondaryColor: "#000000"},
	"Cleveland Guardians":   {PrimaryColor: "#E31937", SecondaryColor: "#0C2340"},
	"Colorado Rockies":      {PrimaryColor: "#33006F", SecondaryColor: "#C4CED4"},
	"Detroit Tigers":        {PrimaryColor: "#0C2340", SecondaryColor: "#FA4616"},
	"Houston Astros":        {PrimaryColor: "#EB6E1F", SecondaryColor: "#002D62"},
	"Kansas City Royals":    {PrimaryColor: "#004687", SecondaryColor: "#BD9B60"},
	"Los Angeles Angels":    {PrimaryColor: "#BA0021", SecondaryColor: "#003263"},
	"Los Angeles Dodgers":   {PrimaryColor: "#005A9C", SecondaryColor: "#EF3E42"},
	"Miami Marlins":         {PrimaryColor: "#00A3E0", SecondaryColor: "#EF3340"},
	"Milwaukee Brewers":     {PrimaryColor: "#0A2351", SecondaryColor: "#B6922E"},
	"Minnesota Twins":       {PrimaryColor: "#002B5C", SecondaryColor: "#D31145"},
	"New York Yankees":      {PrimaryColor: "#003087", SecondaryColor: "#E4002C"},
	"New York Mets":         {PrimaryColor: "#002D72", SecondaryColor: "#FF5910"},
	"Oakland Athletics":     {PrimaryColor: "#003831", SecondaryColor: "#EFB21E"},
	"Philadelphia Phillies": {PrimaryColor: "#E81828", SecondaryColor: "#002D72"},
	"Pittsburgh Pirates":    {PrimaryColor: "#FFC72C", SecondaryColor: "#27251F"},
	"San Diego Padres":      {PrimaryColor: "#002D62", SecondaryColor: "#A2AAAD"},
	"San Francisco Giants":  {PrimaryColor: "#FD5A1E", SecondaryColor: "#27251F"},
	"Seattle Mariners":      {PrimaryColor: "#005C5C", SecondaryColor: "#C4CED4"},
	"St. Louis Cardinals":   {PrimaryColor: "#C41E3A", SecondaryColor: "#0C2340"},
	"Tampa Bay Rays":        {PrimaryColor: "#092C5C", SecondaryColor: "#8FBCE6"},
	"Texas Rangers":         {PrimaryColor: "#003278", SecondaryColor: "#C0111F"},
	"Toronto Blue Jays":     {PrimaryColor: "#134A8E", SecondaryColor: "#1D2D5C"},
	"Washington Nationals":  {PrimaryColor: "#AB0003", SecondaryColor: "#14225A"},
}
