/*
 * Copyright (c) 2024 dos-2
 * All rights reserved.
 */
package colors

import "oddshub/models"

var NCAATeamColorMap = map[string]models.TeamColors{
	"Air Force Falcons":                   {PrimaryColor: "#004A7F", SecondaryColor: "#FFFFFF"},
	"Akron Zips":                          {PrimaryColor: "#0D254C", SecondaryColor: "#A7A9AC"},
	"Alabama Crimson Tide":                {PrimaryColor: "#A32638", SecondaryColor: "#000000"},
	"Alabama State":                       {PrimaryColor: "#FFB612", SecondaryColor: "#000000"},
	"Alcorn State":                        {PrimaryColor: "#E41E3D", SecondaryColor: "#000000"},
	"Appalachian State Mountaineers":      {PrimaryColor: "#000000", SecondaryColor: "#FFD110"},
	"Arizona State Sun Devils":            {PrimaryColor: "#8C1D40", SecondaryColor: "#FFC627"},
	"Arizona Wildcats":                    {PrimaryColor: "#002A5C", SecondaryColor: "#A71930"},
	"Arkansas Pine Bluff":                 {PrimaryColor: "#9E1B32", SecondaryColor: "#E2D7D5"},
	"Arkansas Razorbacks":                 {PrimaryColor: "#9D2235", SecondaryColor: "#000000"},
	"Army Black Knights":                  {PrimaryColor: "#D0C9C0", SecondaryColor: "#000000"},
	"Auburn Tigers":                       {PrimaryColor: "#03244D", SecondaryColor: "#E87722"},
	"Ball State Cardinals":                {PrimaryColor: "#CE1141", SecondaryColor: "#FFFFFF"},
	"Baylor Bears":                        {PrimaryColor: "#003015", SecondaryColor: "#FFC20E"},
	"Boise State Broncos":                 {PrimaryColor: "#0033A0", SecondaryColor: "#CDB87D"},
	"Boston College Eagles":               {PrimaryColor: "#98002E", SecondaryColor: "#A67B5B"},
	"Bowling Green Falcons":               {PrimaryColor: "#FFCC00", SecondaryColor: "#006341"},
	"Buffalo Bulls":                       {PrimaryColor: "#00539B", SecondaryColor: "#FFFFFF"},
	"BYU Cougars":                         {PrimaryColor: "#002E5D", SecondaryColor: "#FFFFFF"},
	"California Golden Bears":             {PrimaryColor: "#003262", SecondaryColor: "#FFB310"},
	"Central Michigan Chippewas":          {PrimaryColor: "#660000", SecondaryColor: "#FFD700"},
	"Charlotte 49ers":                     {PrimaryColor: "#00703C", SecondaryColor: "#FFB81C"},
	"Chicago State":                       {PrimaryColor: "#C8102E", SecondaryColor: "#FFC72C"},
	"Cincinnati Bearcats":                 {PrimaryColor: "#E00122", SecondaryColor: "#000000"},
	"Clemson Tigers":                      {PrimaryColor: "#F56600", SecondaryColor: "#522D80"},
	"Coastal Carolina Chanticleers":       {PrimaryColor: "#0060A8", SecondaryColor: "#FDB827"},
	"Colorado Buffaloes":                  {PrimaryColor: "#CFB87C", SecondaryColor: "#000000"},
	"Colorado State Rams":                 {PrimaryColor: "#00519D", SecondaryColor: "#FFC425"},
	"Connecticut Huskies":                 {PrimaryColor: "#0F2439", SecondaryColor: "#C4CED4"},
	"Creighton Bluejays":                  {PrimaryColor: "#005CA9", SecondaryColor: "#B2B4B2"},
	"Drake Bulldogs":                      {PrimaryColor: "#002D72", SecondaryColor: "#C8102E"},
	"Duke Blue Devils":                    {PrimaryColor: "#00539B", SecondaryColor: "#001A57"},
	"Duquesne Dukes":                      {PrimaryColor: "#003E7E", SecondaryColor: "#FFFFFF"},
	"East Carolina Pirates":               {PrimaryColor: "#4B9CD3", SecondaryColor: "#FDB927"},
	"Eastern Michigan Eagles":             {PrimaryColor: "#17469E", SecondaryColor: "#C4CED4"},
	"Florida International Panthers":      {PrimaryColor: "#00205B", SecondaryColor: "#B9975B"},
	"Florida Atlantic Owls":               {PrimaryColor: "#00519B", SecondaryColor: "#d21034"},
	"Florida Gators":                      {PrimaryColor: "#0021A5", SecondaryColor: "#FA4616"},
	"Florida State Seminoles":             {PrimaryColor: "#782F40", SecondaryColor: "#CEB888"},
	"Florida St Seminoles":                {PrimaryColor: "#782F40", SecondaryColor: "#CEB888"},
	"Fresno State Bulldogs":               {PrimaryColor: "#0033A0", SecondaryColor: "#FDB515"},
	"Georgia Bulldogs":                    {PrimaryColor: "#BA0C2F", SecondaryColor: "#000000"},
	"Georgia Southern Eagles":             {PrimaryColor: "#003DA5", SecondaryColor: "#C5B783"},
	"Georgia State Panthers":              {PrimaryColor: "#003366", SecondaryColor: "#000000"},
	"Georgia Tech Yellow Jackets":         {PrimaryColor: "#00223E", SecondaryColor: "#FFCC00"},
	"Georgetown Hoyas":                    {PrimaryColor: "#002651", SecondaryColor: "#5C6670"},
	"Gonzaga Bulldogs":                    {PrimaryColor: "#003366", SecondaryColor: "#FFFFFF"},
	"Grand Canyon Antelopes":              {PrimaryColor: "#512888", SecondaryColor: "#FFD100"},
	"Hawaii Rainbow Warriors":             {PrimaryColor: "#024731", SecondaryColor: "#CFB87C"},
	"Houston Cougars":                     {PrimaryColor: "#C8102E", SecondaryColor: "#000000"},
	"Idaho Vandals":                       {PrimaryColor: "#FF6600", SecondaryColor: "#000000"},
	"Illinois Fighting Illini":            {PrimaryColor: "#E84A27", SecondaryColor: "#13294B"},
	"Indiana Hoosiers":                    {PrimaryColor: "#990000", SecondaryColor: "#FFFFFF"},
	"Iowa Hawkeyes":                       {PrimaryColor: "#000000", SecondaryColor: "#FFD100"},
	"Iowa State Cyclones":                 {PrimaryColor: "#C8102E", SecondaryColor: "#F1BE48"},
	"Jackson State":                       {PrimaryColor: "#00205B", SecondaryColor: "#FFD700"},
	"Jacksonville State Gamecocks":        {PrimaryColor: "#C8102E", SecondaryColor: "#FFFFFF"},
	"James Madison Dukes":                 {PrimaryColor: "#00703C", SecondaryColor: "#FFD100"},
	"Kansas Jayhawks":                     {PrimaryColor: "#0051BA", SecondaryColor: "#FFCD00"},
	"Kansas State Wildcats":               {PrimaryColor: "#512888", SecondaryColor: "#FFFFFF"},
	"Kennsaw State Owls":                  {PrimaryColor: "#000000", SecondaryColor: "#FFD100"},
	"Kent State Golden Flashes":           {PrimaryColor: "#002147", SecondaryColor: "#FDB813"},
	"Kentucky Wildcats":                   {PrimaryColor: "#005DAA", SecondaryColor: "#FFFFFF"},
	"Longwood":                            {PrimaryColor: "#2A74AD", SecondaryColor: "#D8D9D7"},
	"Louisiana Ragin Cajuns":              {PrimaryColor: "#CE181E", SecondaryColor: "#000000"},
	"Louisiana Tech Bulldogs":             {PrimaryColor: "#00205B", SecondaryColor: "#C8102E"},
	"Louisville Cardinals":                {PrimaryColor: "#AD0000", SecondaryColor: "#000000"},
	"LSU Tigers":                          {PrimaryColor: "#461D7C", SecondaryColor: "#FDD023"},
	"Marshall Thundering Herd":            {PrimaryColor: "#0066CC", SecondaryColor: "#C8102E"},
	"Marquette Golden Eagles":             {PrimaryColor: "#003366", SecondaryColor: "#FDB813"},
	"Maryland Terrapins":                  {PrimaryColor: "#FFCD00", SecondaryColor: "#000000"},
	"Maryland Eastern Shore":              {PrimaryColor: "#FDB827", SecondaryColor: "#000000"},
	"Memphis Tigers":                      {PrimaryColor: "#231F20", SecondaryColor: "#4D1979"},
	"Miami Hurricanes":                    {PrimaryColor: "#005030", SecondaryColor: "#F47321"},
	"Miami (Oh) RedHawks":                 {PrimaryColor: "#BE020D", SecondaryColor: "#003C71"},
	"Michigan State Spartans":             {PrimaryColor: "#18453B", SecondaryColor: "#FFFFFF"},
	"Michigan Wolverines":                 {PrimaryColor: "#00274C", SecondaryColor: "#FFCB05"},
	"Middle Tennessee State Blue Raiders": {PrimaryColor: "#006A4D", SecondaryColor: "#FFFFFF"},
	"Minnesota Golden Gophers":            {PrimaryColor: "#7A0019", SecondaryColor: "#FFD100"},
	"Mississippi State Bulldogs":          {PrimaryColor: "#660000", SecondaryColor: "#FFFFFF"},
	"Missouri Tigers":                     {PrimaryColor: "#000000", SecondaryColor: "#FFD100"},
	"Mount St Marys":                      {PrimaryColor: "#003087", SecondaryColor: "#FFFFFF"},
	"Navy Midshipmen":                     {PrimaryColor: "#00205B", SecondaryColor: "#FDB515"},
	"NC State Wolfpack":                   {PrimaryColor: "#CC0000", SecondaryColor: "#000000"},
	"Nebraska Cornhuskers":                {PrimaryColor: "#E41C38", SecondaryColor: "#000000"},
	"Nevada Wolf Pack":                    {PrimaryColor: "#002654", SecondaryColor: "#C8102E"},
	"New Mexico Lobos":                    {PrimaryColor: "#BA0C2F", SecondaryColor: "#000000"},
	"New Mexico State Aggies":             {PrimaryColor: "#8B1107", SecondaryColor: "#000000"},
	"North Carolina A T":                  {PrimaryColor: "#00853E", SecondaryColor: "#FFD200"},
	"North Carolina Central":              {PrimaryColor: "#AB0122", SecondaryColor: "#FFFFFF"},
	"North Carolina Tar Heels":            {PrimaryColor: "#7BAFD4", SecondaryColor: "#FFFFFF"},
	"North Dakota State Bison":            {PrimaryColor: "#006A4D", SecondaryColor: "#FFD100"},
	"North Texas Mean Green":              {PrimaryColor: "#00853E", SecondaryColor: "#00703C"},
	"Northern Colorado":                   {PrimaryColor: "#004B8D", SecondaryColor: "#FFFFFF"},
	"Northern Illinois Huskies":           {PrimaryColor: "#F47321", SecondaryColor: "#000000"},
	"Northwestern Wildcats":               {PrimaryColor: "#4E2A84", SecondaryColor: "#FFFFFF"},
	"Notre Dame Fighting Irish":           {PrimaryColor: "#0C2340", SecondaryColor: "#AE9142"},
	"Ohio Bobcats":                        {PrimaryColor: "#006A4D", SecondaryColor: "#FFFFFF"},
	"Ohio State Buckeyes":                 {PrimaryColor: "#BB0000", SecondaryColor: "#DDDDDD"},
	"Oklahoma Sooners":                    {PrimaryColor: "#841617", SecondaryColor: "#f9f3d9"},
	"Oklahoma State Cowboys":              {PrimaryColor: "#FF7300", SecondaryColor: "#000000"},
	"Old Dominion Monarchs":               {PrimaryColor: "#00478E", SecondaryColor: "#FFFFFF"},
	"Ole Miss Rebels":                     {PrimaryColor: "#00205B", SecondaryColor: "#C8102E"},
	"Oregon Ducks":                        {PrimaryColor: "#154733", SecondaryColor: "#FFCC00"},
	"Oregon State Beavers":                {PrimaryColor: "#DC4405", SecondaryColor: "#000000"},
	"Penn State Nittany Lions":            {PrimaryColor: "#041E42", SecondaryColor: "#FFFFFF"},
	"Pittsburgh Panthers":                 {PrimaryColor: "#1C2D7C", SecondaryColor: "#FFB81C"},
	"Prairie View A M":                    {PrimaryColor: "#008E3E", SecondaryColor: "#FFC72C"},
	"Providence Friars":                   {PrimaryColor: "#000000", SecondaryColor: "#FFFFFF"},
	"Purdue Boilermakers":                 {PrimaryColor: "#000000", SecondaryColor: "#C8102E"},
	"Rice Owls":                           {PrimaryColor: "#FFFFFF", SecondaryColor: "#00205B"},
	"Rutgers Scarlet Knights":             {PrimaryColor: "#CC0033", SecondaryColor: "#FFFFFF"},
	"Sam Houston State Bearkats":          {PrimaryColor: "#FFD100", SecondaryColor: "#000000"},
	"San Diego State Aztecs":              {PrimaryColor: "#000066", SecondaryColor: "#C41230"},
	"San Jose State Spartans":             {PrimaryColor: "#005C8E", SecondaryColor: "#FFC72C"},
	"Seton Hall Pirates":                  {PrimaryColor: "#004488", SecondaryColor: "#FFFFFF"},
	"SMU Mustangs":                        {PrimaryColor: "#9E1B32", SecondaryColor: "#FFFFFF"},
	"South Alabama Jaguars":               {PrimaryColor: "#004B8D", SecondaryColor: "#FFA300"},
	"South Carolina Gamecocks":            {PrimaryColor: "#73000A", SecondaryColor: "#000000"},
	"South Dakota State Jackrabbits":      {PrimaryColor: "#003087", SecondaryColor: "#FFD100"},
	"South Florida Bulls":                 {PrimaryColor: "#006747", SecondaryColor: "#FFFFFF"},
	"Southern Mississippi Golden Eagles":  {PrimaryColor: "#FFC72C", SecondaryColor: "#000000"},
	"Stanford Cardinal":                   {PrimaryColor: "#8C1515", SecondaryColor: "#FFFFFF"},
	"St Johns Red Storm":                  {PrimaryColor: "#FF0000", SecondaryColor: "#FFFFFF"},
	"Syracuse Orange":                     {PrimaryColor: "#D44500", SecondaryColor: "#2D2926"},
	"TCU Horned Frogs":                    {PrimaryColor: "#4D1979", SecondaryColor: "#FFFFFF"},
	"Temple Owls":                         {PrimaryColor: "#9D2235", SecondaryColor: "#000000"},
	"Tennessee State":                     {PrimaryColor: "#002A5C", SecondaryColor: "#FFFFFF"},
	"Tennessee Volunteers":                {PrimaryColor: "#FF8200", SecondaryColor: "#FFFFFF"},
	"Texas Longhorns":                     {PrimaryColor: "#BF5700", SecondaryColor: "#FFFFFF"},
	"Texas A&M Aggies":                    {PrimaryColor: "#500000", SecondaryColor: "#FFFFFF"},
	"Texas A&M Corpus Christi":            {PrimaryColor: "#14458A", SecondaryColor: "#8E9C9E"},
	"Texas State Bobcats":                 {PrimaryColor: "#660000", SecondaryColor: "#FFFFFF"},
	"Texas Tech Red Raiders":              {PrimaryColor: "#CC0000", SecondaryColor: "#000000"},
	"Toledo Rockets":                      {PrimaryColor: "#003087", SecondaryColor: "#FFCD00"},
	"Troy Trojans":                        {PrimaryColor: "#872434", SecondaryColor: "#FFFFFF"},
	"Tulane Green Wave":                   {PrimaryColor: "#006747", SecondaryColor: "#FFFFFF"},
	"Tulsa Golden Hurricane":              {PrimaryColor: "#C9A000", SecondaryColor: "#004730"},
	"UCF Knights":                         {PrimaryColor: "#BA9B37", SecondaryColor: "#000000"},
	"UCLA Bruins":                         {PrimaryColor: "#2D68C4", SecondaryColor: "#FFC72C"},
	"UConn Huskies":                       {PrimaryColor: "#0F2439", SecondaryColor: "#C4CED4"},
	"UMass Lowell":                        {PrimaryColor: "#00543D", SecondaryColor: "#A9AFB3"},
	"UMass Minutemen":                     {PrimaryColor: "#881E3D", SecondaryColor: "#FFFFFF"},
	"UNLV Rebels":                         {PrimaryColor: "#000000", SecondaryColor: "#C8102E"},
	"USC Trojans":                         {PrimaryColor: "#990000", SecondaryColor: "#FFCC00"},
	"Utah Utes":                           {PrimaryColor: "#CC0000", SecondaryColor: "#FFFFFF"},
	"Utah State Aggies":                   {PrimaryColor: "#003263", SecondaryColor: "#FFFFFF"},
	"UTEP Miners":                         {PrimaryColor: "#FF8200", SecondaryColor: "#041E42"},
	"UTSA Roadrunners":                    {PrimaryColor: "#004B8D", SecondaryColor: "#FF8200"},
	"Vanderbilt Commodores":               {PrimaryColor: "#866D4B", SecondaryColor: "#FFFFFF"},
	"Virginia Cavaliers":                  {PrimaryColor: "#00467F", SecondaryColor: "#F84C1E"},
	"Virginia Tech Hokies":                {PrimaryColor: "#660000", SecondaryColor: "#FFFFFF"},
	"Wake Forest Demon Deacons":           {PrimaryColor: "#9E7E38", SecondaryColor: "#000000"},
	"Washington Huskies":                  {PrimaryColor: "#4B2E83", SecondaryColor: "#B7A57A"},
	"Washington State Cougars":            {PrimaryColor: "#981E32", SecondaryColor: "#000000"},
	"West Virginia Mountaineers":          {PrimaryColor: "#EAAA00", SecondaryColor: "#003366"},
	"Western Kentucky Hilltoppers":        {PrimaryColor: "#F32026", SecondaryColor: "#FFFFFF"},
	"Western Michigan Broncos":            {PrimaryColor: "#8C213E", SecondaryColor: "#FFC61E"},
	"Wisconsin Badgers":                   {PrimaryColor: "#C5050C", SecondaryColor: "#000000"},
	"Wyoming Cowboys":                     {PrimaryColor: "#4B286D", SecondaryColor: "#FFFFFF"},
	"Xavier Musketeers":                   {PrimaryColor: "#005030", SecondaryColor: "#FFFFFF"},
}
